### ISSUE TITLE
Create dashboard for other naoqi robot

### ISSUE THREAD

**Issue by k-okada** [ros-naoqi/nao_viz#2]
i'm just writing dashboard for a pepper robot and would line to contribute, questions are
A:
1 should we rename nao_dashboard package to naoqi_dashboard and put these files? 
2 create pepper_dashboaed package in addition to nao_dashboaed package?
3 create naoqi_dashboard package as an abatruct packge and nao_dashboard and pepper_dashboard as an implement packge?

B should be create naoqi_viz repo? Or move xx_dashboard package to naoqi_bridge packge?

**Comment by vrabaud** [comment]
Sorry, I was not a watcher on that repo ....
Trunk is actually robot agnostic now so that bug is now irrelevant (and the package got renamed to naoqi_dashboard).
I am about to rename that repo to naoqi_dashboard (from nao_viz).
I'll release it as soon as I include the stiffness and life APIs.
